DWAPlannerROS:
   max_vel_x: 0.5
   min_vel_x: 0.1
   max_vel_theta: 0.3
   min_vel_theta: -0.3 
   min_in_place_vel_theta: 0.3

   escape_vel: -0.2
   acc_lim_x: 0.5
   acc_lim_th: 1.0

   meter_scoring: true