local_costmap:
   global_frame: odom
   robot_base_frame: base_footprint
   update_frequency: 5
   publish_frequency: 2
   # static_map: false
   rolling_window: true
   width: 1.5
   height: 1.5

   # plugins:
   # - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
   # - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}

   plugins: 
      - {name: obstacles,        type: "costmap_2d::VoxelLayer"}
      - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}